"""Add admin fields to User model

Revision ID: 3a6ce0b2b1b3
Revises: 71cd39827c23
Create Date: 2025-05-18 12:08:59.075875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6ce0b2b1b3'
down_revision = '71cd39827c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('account_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notes')
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
