"""Add download link tracking fields

Revision ID: 5a08ee2cc3d4
Revises: 3dbb76d3cafe
Create Date: 2025-05-18 13:40:38.958919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a08ee2cc3d4'
down_revision = '3dbb76d3cafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentation_attempts', sa.Column('download_link_created', sa.DateTime(), nullable=True))
    op.add_column('presentation_attempts', sa.Column('download_link_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentation_attempts', 'download_link_expires')
    op.drop_column('presentation_attempts', 'download_link_created')
    # ### end Alembic commands ###
